# Generated by Django 4.2.1 on 2023-05-30 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("recipes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор рецепта",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingridients",
            field=models.ManyToManyField(
                through="recipes.IngridientRecipe", to="recipes.ingredient"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recipes.tag"
            ),
        ),
        migrations.AddField(
            model_name="ingridientrecipe",
            name="ingridient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingridient_recipe",
                to="recipes.ingredient",
            ),
        ),
        migrations.AddField(
            model_name="ingridientrecipe",
            name="recepie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_ingridient",
                to="recipes.recipe",
            ),
        ),
    ]
