# Generated by Django 4.2.1 on 2023-06-07 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ("-recipe__created",),
                "verbose_name": "избранный рецепт",
                "verbose_name_plural": "избранные рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "ordering": ("name",),
                "verbose_name": "ингридиент",
                "verbose_name_plural": "ингридиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredientrecipe",
            options={
                "ordering": ("-recipe__created",),
                "verbose_name": "ингредиент в рецепте",
                "verbose_name_plural": "ингридиенты в рецепте",
            },
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("-created",),
                "verbose_name": "рецепт",
                "verbose_name_plural": "рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "ordering": ("-recipe__created",),
                "verbose_name": "список покупок",
                "verbose_name_plural": "списки покупок",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("name",),
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
    ]
