# Generated by Django 4.2.1 on 2023-06-07 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={
                "ordering": ("-author__id",),
                "verbose_name": "подписка",
                "verbose_name_plural": "подписки",
            },
        ),
    ]
